---
title: "Coastwide analysis of forestry impacts on BC Pacific Salmon - Models"
author: ''
date: "Nov 2024"
output:
  html_document:
    collapsed: false
    fig_caption: true
    highlight: espresso
    number_sections: true
    smooth_scroll: true
    theme: sandstone
    toc: true
    toc_float: true
  pdf_document:
    toc: true
  word_document:
    toc: true
---

```{=html}
<style type="text/css">

body{ /* Normal  */
      font-size: 13px;
  }
td {  /* Table  */
  font-size: 13px;
}
h1.title {
  font-size: 24px;
  color: Black;
}
h1 { /* Header 1 */
  font-size: 19px;
  color: Black;
}
h2 { /* Header 2 */
    font-size: 15px;
  color: Black;
}
h3 { /* Header 3 */
    font-size: 15px;
  color: Black;
}
</style>
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(cache=FALSE)
options(max.print=23)
library(cmdstanr)
library(here);library(dplyr); library(stringr)
library(ggplot2)
library(tidyverse)
library(bayesplot)
library(patchwork)
library(hues)
library(GGally)
```

# Model Equations

## Beverton-Holt (BH) with forestry effect on growth rate:

Model with time varying productivity:
$log(R_{t,r}/S_{t,r}) = \alpha_t + \alpha_r - log(1+\frac{(e^{\alpha_t+\alpha_r})}{R_{k,r}}*S_{t,r}) + \beta_{for,r}*X_{t,r} + \epsilon_{t,r}$

Model with static productivity:
$log(R_{t,r}/S_{t,r}) = \alpha_r - log(1+(\frac{(e^{\alpha_t+\alpha_r})}{R_{k,r}})*S_{t,r}) + \beta_{for,r}*X_{t,r} + \epsilon_{t,r}$

Model with ocean covariates:
$log(R_{t,r}/S_{t,r}) = \alpha_r - log(1+\frac{(e^{\alpha_t+\alpha_r})}{R_{k,r}}*S_{t,r}) + \beta_{for,r}*X_{t,r} + \beta_{npgo,r}*Y_{t} + \beta_{sst,r}*Z_{t,r} + \epsilon_{t,r}$

## Ricker with forestry effect on growth rate:

Model with time varying productivity:
$log(R_{t,r}/S_{t,r}) = \alpha_t + \alpha_r - \frac{S_{t,r}}{Smax_r} + \beta_{for,r}*X_{t,r} + \epsilon_{t,r}$

Model with static productivity:
$log(R_{t,r}/S_{t,r}) = \alpha_r - \frac{S_{t,r}}{Smax_r} + \beta_{for,r}*X_{t,r} + \epsilon_{t,r}$

Model with ocean covariates:
$log(R_{t,r}/S_{t,r}) = \alpha_r - \frac{S_{t,r}}{Smax_r} + \beta_{for,r}*X_{t,r} + \beta_{npgo,r}*Y_{t} + \beta_{sst,r}*Z_{t,r} + \epsilon_{t,r}$

## Beverton-Holt (BH) with forestry effect on carrying capacity:

$log(R_{t,r}/S_{t,r}) = log(r_r) - log(1+\frac{(r_r - 1)}{K_{t,r}} * S_{t,r})  + \beta_{npgo,r}*Y{t} + \beta_{sst,r}*Z{t,r} + \epsilon_{t,r}$
$K_{t,r} = K_r + \beta_{for,r}*X_{t,r}$

Prior on $K_r$

$K_{t,r} = K_r + \beta_{for,r}*X_{t,r}$

$K_r \sim lognormal(S_{mean,r}, 5*S_{mean,r})$

## Ricker with forestry effect on carrying capacity:

<!-- $log(R_{t,r}/S_{t,r}) = r_r - \frac{r_r}{(K_{t,r}+ \beta_{for,r}*X_{t,r})}*S_{t,r} + \beta_{npgo,r}*Y_{t} + \beta_{sst,r}*Z_{t,r} + \epsilon_{t,r}$ -->

<!-- $log(R_{t,r}/S_{t,r}) = r_r - \frac{r_r}{K_{t,r}}*S_{t,r} + \beta_{for,r}*X_{t,r}*S_{t,r} + \beta_{npgo,r}*Y_{t} + \beta_{sst,r}*Z_{t,r} + \epsilon_{t,r}$ -->

$log(R_{t,r}/S_{t,r}) = r_r - \frac{r_r}{(K_{t,r})}*S_{t,r} + \beta_{npgo,r}*Y_{t} + \beta_{sst,r}*Z_{t,r} + \epsilon_{t,r}$


Prior on $K_r$

$K_{t,r} = K_r + \beta_{for,r}*X_{t,r}$

$K_r \sim lognormal(S_{mean,r}, 5*S_{mean,r})$

